# Numpy

In [1]:
#código comparando a velocidade de excecucao do numpy com os tipos builtins do python
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

1.04 ms ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

53.2 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
list1 = [0,1,2,3,4]
arr1d = np.array(list1)
# principal diferença entre list e array
print(arr1d + 2)
print(list1 + 2)  # erro

[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [6]:
arr1d

array([0, 1, 2, 3, 4])

In [7]:
type(arr1d)

numpy.ndarray

In [8]:
x = [1,2,3,4.5,5.7]
print('--------- lists ----------\n')
print(type(x))
print(x)
print(type(x[1]))
print(type(x[4]))
print('\n')
print('--------- array ----------\n')
y = np.array(x)
print(type(y))
print(y)
print(type(y[1]))
print(type(y[4]))

--------- lists ----------

<class 'list'>
[1, 2, 3, 4.5, 5.7]
<class 'int'>
<class 'float'>


--------- array ----------

<class 'numpy.ndarray'>
[1.  2.  3.  4.5 5.7]
<class 'numpy.float64'>
<class 'numpy.float64'>


## ndarray

In [9]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
print(arr1.shape)
print(arr1.dtype)

(5,)
float64


In [11]:
arr1[0] = 7
arr2 = list(arr1)
type(arr2)

list

In [12]:
arr2.append(9)
np.array(arr2)

array([7. , 7.5, 8. , 0. , 1. , 9. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)
print()
print(arr2.dtype)
print()
print(arr2.size)

[[1 2 3 4]
 [5 6 7 8]]

2

(2, 4)

int32

8


In [18]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print()
print(data4)
print()
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[6.  7.5]
 [8.  1. ]]


In [21]:
data6 = np.arange(0, 15, 2)
print(data6)

[ 0  2  4  6  8 10 12 14]


In [22]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [25]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre arrays e escalares

In [27]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print()
print('Escalar dividindo array: \n',1/arr3)
print()
print('Tirando Raiz quadrada de cada elemento: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]

Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Tirando Raiz quadrada de cada elemento: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Fatiamento

In [31]:
#arr = [2,14,3,6,8,3,10,222,4]
arr = np.arange(10)
print(arr)
print()
print(arr[5])
print()
print(arr[5:8])
print()
arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]

5

[5 6 7]

[ 0  1  2  3  4 12 12 12  8  9]


In [ ]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

In [33]:
print(["abc"] * 3)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print()
print(arr2d[2])
print()
print(arr2d[2][2]) #igual a print(arr2d[0, 2])

['abc', 'abc', 'abc']
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]

9


In [ ]:
arr2d[:2,1:]

In [ ]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [ ]:
names == "Bob"

In [ ]:
data[names == "Bob"]

In [ ]:
~(names == "Bob")

In [ ]:
data[~(names == "Bob")]

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask

In [ ]:
data[mask]

## TODO

### 1)

Seja um array, A = [10,3,7,5,8,23,15] e dois escalares, x = 6, y = 20. 

Crie uma função que retorne um novo array contendo elementos no intervalo [6,20]

In [70]:
# Resposta
import numpy as np
def intervalo(arr, x, y):
    mask = (arr >= x) & (arr <= y)
    return arr[mask].sort()

vetor = np.array([10,3,7,5,8,23,15])
intervalo(vetor, 6, 20)
    

## 2)

Escreva um programa usando Numpy que adiciona os valores de um vetor a cada linha de uma matriz. 

Obs: o tamanho do vetor tem de ser o mesmo da quantidade de linhas

vetor = [ 1 1 0]

matriz = [[1 2 3]; [4 5 6]; [7 8 9]]

resultado = [[2 3 3; 5 6 6; 8 9 9]]


Essa função pode ajudar: np.empty_like() 

In [68]:
# Resposta
def adicionar(vetor, matriz):
    return vetor + matriz
#    np_vetor = np.array(vetor)
#    np_matriz = np.array(matriz)
    
#    for line in range(0, np_matriz.shape[0]):
#        np_matriz[line] = np_matriz[line] + np_vetor

#    return np_matriz

print(adicionar(np.array([1, 1, 0]), np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])))
#print(adicionar([10, 10, 10], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[[2 3 3]
 [5 6 6]
 [8 9 9]]


## Transposição

In [72]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print()
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Flattening

In [ ]:
arr2d

In [ ]:
print('----- flatten() -----\n')
print(arr2d.flatten())
b1 = arr2d.flatten() 
b1[0] = 100
print(arr2d,'\n')
print('----- ravel() -----\n')
b2 = arr2d.ravel() 
b2[0] = 101
print(arr2d)

## Funções Universais

In [ ]:
arr = np.arange(10)
print(arr)
print(np.sqrt(arr)) #raiz quadrada
print()
np.exp(arr) #e^x

## Localização baseada em Condição e Métodos Estatísticos

In [ ]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
print()
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print()
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

In [ ]:
arr = np.random.randn(5, 4)
print(arr)
print()
print(arr.mean()) #ou np.mean(arr)
print()
print(arr.sum())
print()
print(arr.mean(axis=1)) #linhas
print()
print(arr.mean(axis=0)) # colunas

 ## Álgebra Linear

In [73]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print()
print(y)
print()
z = np.matmul(x,y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


In [74]:
print(x.shape)
print(y.shape)
print(z.shape)

(2, 3)
(3, 2)
(2, 2)


In [75]:
import numpy as np
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = np.matmul(X.T,X) #transposta * X
print()
print(mat)
print()
print(inv(mat)) #inversa

[[ 1.21013996  0.37298446 -1.67144133 -0.72941389  0.73832627]
 [-0.8729542  -0.16578753  1.22985068  0.97625391 -0.02958121]
 [-0.60548569  0.97472725  0.78457668  0.31548049  0.10603247]
 [-0.23737667 -0.5270108   2.13101653 -2.13747836 -0.20060565]
 [-0.29343332  1.05340052 -1.82047562 -1.5547206   0.94668129]]

[[ 2.73555147 -0.17809783 -3.54299661 -0.96234246  0.62493128]
 [-0.17809783  2.50408914 -3.10332595 -0.63767264  1.48659706]
 [-3.54299661 -3.10332595 12.77717231  0.94266692 -3.33816305]
 [-0.96234246 -0.63767264  0.94266692  8.57061416 -1.5770077 ]
 [ 0.62493128  1.48659706 -3.33816305 -1.5770077   1.4936917 ]]

[[ 0.97472921  0.54909123  0.43450633  0.13105258  0.1551242 ]
 [ 0.54909123  1.5216715   0.08670939 -0.14886013 -1.70755459]
 [ 0.43450633  0.08670939  0.44409075  0.17336085  0.90741629]
 [ 0.13105258 -0.14886013  0.17336085  0.23544941  0.72933958]
 [ 0.1551242  -1.70755459  0.90741629  0.72933958  5.10197742]]


## Geração de Números Aleatórios

#### Você pode ver todas as distribuições nesse link: [numpy random](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [76]:
# gera 4 números aleatórios
# entre [0.0,1.0)
samples = np.random.random(4)
samples

array([0.97914941, 0.75586162, 0.38606588, 0.76002547])

In [77]:
# A geração de números é determinística
# Ou seja, é baseada num estado interno
# que chamamos de seed
np.random.seed(42) # set seed
print(np.random.random())
np.random.seed(0) # reset seed
print()
print(np.random.random())

0.3745401188473625

0.5488135039273248


In [90]:
# shuffle reordena um array
# é muito usado antes do processo
# de treino de algoritmo de ML
x = np.arange(10)
np.random.shuffle(x)
x

array([4, 6, 1, 8, 9, 5, 7, 2, 3, 0])

## Vectorize

In [ ]:
import numpy as np

In [91]:
def modulo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
    
print('x = 10 retorna ', modulo(10))
print('x = 11 retorna ', modulo(11))
print('x = [10, 11, 12] retorna ', modulo([10, 11, 12])) # Erro

x = 10 retorna  5.0
x = 11 retorna  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [92]:
modulo_vect = np.vectorize(modulo, otypes=[float])

print('x = [10, 11, 12] retorna ', modulo_vect([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] retorna ', modulo_vect([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] retorna  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] retorna  [[  5. 121.   6.]
 [  1.   1.   9.]]


## Aplicar uma função – coluna ou linha

In [93]:
#criando matriz
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [ ]:
#função que calcula diferença
def max_minus_min(x):
    return np.max(x) - np.min(x)

# aplicando nas linhas
print('Por linha: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

# aplicando nas colunas
print('Por coluna: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

In [ ]:
vet = np.array([3,6,8,9,11])
np.min(vet)

## Outros Métodos

In [ ]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

In [ ]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place arr = arr.sort()
print(arr)

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## TODO Section

### 3)
Suponha dois arrays, A = [1,4,2,6,5,7,3,0] e B = [3,2,0,9,8,7]. 

Remove de A todo elemento pertencente a B


In [102]:
# resposta
A = [1,4,2,6,5,7,3,0]
B = [3,2,0,9,8,7]

result = [a for a in A if a in B]
result

[2, 7, 3, 0]

### 4)

A célula abaixo faz o download de um dataset e armazena na variável iris_2d. Em seguida, substitui alguns de seus elementos por NaN. Resolva as questões que se seguem:

In [103]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [129]:
iris_2d = np.array(iris_2d)
iris_2d

array([[5.1, 3.5, nan, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, nan, nan, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [nan, 3.5, 1.4, nan],
       [5.7, 3.8, 1.7, nan],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [nan, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

a) Encontre o número de NaN na primeira coluna

b) Encontre o número total de NaN

c) Encontre as posições (número da linha) de NaN na primeira coluna

d) Substitua todos os NaN por 0

In [138]:
# Resposta A
import numpy as np
np.isnan(iris_2d[:,0]).sum()

5

In [140]:
# Resposta B
np.isnan(iris_2d[:,:]).sum()

20

In [152]:
# Resposta C
#mask = np.isnan(iris_2d[:,0])
#np.array(list(range(0,len(iris_2d))))[mask]
np.where(np.isnan(iris_2d[:,0]))

(array([ 17,  30,  53,  70, 106], dtype=int64),)

In [159]:
# Resposta D
def nan_2_zero(valor):
    if np.isnan(valor):
        return 0
    else:
        return valor

nan_2_zero_vect = np.vectorize(nan_2_zero)

nan_2_zero_vect(iris_2d)

array([[5.1, 3.5, 0. , 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 0. , 0. , 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [0. , 3.5, 1.4, 0. ],
       [5.7, 3.8, 1.7, 0. ],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [0. , 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [157]:
# Resposta D (segunda opção)

np.where(np.isnan(iris_2d), 0, iris_2d)

array([[5.1, 3.5, 0. , 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 0. , 0. , 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [0. , 3.5, 1.4, 0. ],
       [5.7, 3.8, 1.7, 0. ],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [0. , 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3