# Random Forest Regressor

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [10]:
dataset = pd.read_csv('bases/50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

### TO-DO 1

Remova as colunas Administration e State do dataset

In [11]:
#resposta
dataset.drop('Administration', axis=1, inplace=True)
dataset.drop('State', axis=1, inplace=True)

### TO-DO 2
Separe o dataset em vetor de características e variável meta

In [33]:
#resposta
from sklearn.model_selection import train_test_split

X = dataset.drop('Profit', axis=1)
y = dataset.Profit

### TO-DO 3
Treine um modelo de regressão usando Regression Tree e outro usando Random Forest Regressor

In [34]:
#resposta Regression Tree
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [35]:
#resposta Regression Tree
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X, y) 

DecisionTreeRegressor(random_state=0)

In [40]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(max_depth=16, random_state=42)
rf_model.fit(X, y)

RandomForestRegressor(max_depth=16, random_state=42)

### TO-DO 4
Suponha que a empresa tenha um orçamento de R$ 500.000,00.

Eles estão considerando três opções:

> R&D: 300.000,00 ; Marketing: 200.000,00

> R&D: 200.000,00 ; Marketing: 300.000,00

> R&D: 100.000,00 ; Marketing: 400.000,00

Qual opção irá, a partir do modelo treinado, retornar o maior lucro? Faça um para cada modelo

In [42]:
# resposta
print('regressor')
print(regressor.predict([[300000, 200000], [200000, 300000], [100000, 400000]]))

print('random forest')
print(rf_model.predict([[300000, 200000], [200000, 300000], [100000, 400000]]))


regressor
[166187.94 166187.94 125370.37]
random forest
[170166.5423 170178.2197 150851.3924]


C:\Users\logonrmlocal\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\logonrmlocal\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


# Random Forest Classifier

In [43]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [44]:
#fazendo o download dos dados direto dos datasets presente na scikit-learn
data = datasets.load_breast_cancer()
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [45]:
#variável meta (target) -> aquilos que estamos tentando prever
#no caso: cancer benigno ou maligno
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [46]:
#linhas x colunas
data.data.shape

(569, 30)

In [47]:
#visualizando as 5 primeiras amostras
data.data[0:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

## TODO 1
> Separe o dataset em conjunto de treino e teste, sendo 70% para treino e 30% para teste

In [54]:
#resposta
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=0) 

## TODO 2
> Treine uma árvore de classificacao nesse conjunto de dados

> faca a predicao do conjunto de teste

> obtenha a Acurácia, Precision, Recall

In [55]:
# resposta
from sklearn.tree import DecisionTreeClassifier
 
tree_clf = DecisionTreeClassifier(max_depth=2, random_state=42)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [59]:
# resposta
y_pred_tree = tree_clf.predict(X_test)

In [64]:
# resposta
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('accuracy: %f' % accuracy_score(y_pred_tree, y_test))
print('precision: %f' % precision_score(y_pred_tree, y_test))
print('recall: %f' % recall_score(y_pred_tree, y_test))


accuracy: 0.947368
precision: 0.944444
recall: 0.971429


## TODO 3
> Treine uma Random Forest Classifier nesse conjunto de dados

> faça a predição do conjunto de teste

> obtenha a Acurácia, Precision, Recall

In [65]:
#resposta
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, random_state=42)
rnd_clf.fit(X_train, y_train)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, random_state=42)

In [66]:
#resposta
y_pred_rf = rnd_clf.predict(X_test)

In [67]:
#resposta
print('accuracy: %f' % accuracy_score(y_pred_rf, y_test))
print('precision: %f' % precision_score(y_pred_rf, y_test))
print('recall: %f' % recall_score(y_pred_rf, y_test))

accuracy: 0.959064
precision: 0.962963
recall: 0.971963
